backend:
  name: github
  repo: zhutou369/deepseek-my
  branch: main
  base_url: https://fragrant-surf-290f.http2019http.workers.dev/
  auth_endpoint: /auth

media_folder: "src/static/assets/img"
public_folder: "/static/assets/img"

display_type: list
show_preview_links: false

collections:
  - name: "posts"
    label: "Artikel"
    folder: "src/posts"
    create: true
    slug: "{{year}}{{month}}{{day}}-{{hour}}{{minute}}{{second}}-{{slug}}"
    fields:
      - {label: "Tajuk", name: "title", widget: "string"}
      - {label: "Penerangan SEO", name: "description", widget: "string"}
      - {label: "Tarikh", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "Kandungan", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "hidden", default: ["posts"]}
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk"}
